import React from 'react'
import { forwardRef } from 'react'


export const Menu1 = forwardRef((props, ref) => {
    return (
      <section ref={ref} className='h-[200px] border-2 border-yellow-600 w-[1535px] '>
        {/* Markup generated by Builder.io */}
        meni1
      </section>
    );
  });