import React from 'react'
import { forwardRef } from 'react'



export const Menu2 = forwardRef((props, ref) => {
    return (
      <section ref={ref} className='h-[200px] border-2 border-yellow-600 w-[300px]'>
        {/* Markup generated by Builder.io */}
        menu2
      </section>
    );
  });
